"""add elo range and girls only to tournaments

Revision ID: 08bcf3322045
Revises: 1055da0a90ac
Create Date: 2026-10-07 09:22:37.256811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bcf3322045'
down_revision: Union[str, Sequence[str], None] = '1055da0a90ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('minElo', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tournaments', sa.Column('maxElo', sa.Integer(), server_default='3000', nullable=False))
    op.add_column('tournaments', sa.Column('girlsOnly', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_check_constraint(
        'elo_range', 'tournaments',
        '"minElo" >= 0 AND "maxElo" <= 3000 AND "minElo" <= "maxElo"',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('elo_range', 'tournaments', type_='check')
    op.drop_column('tournaments', 'girlsOnly')
    op.drop_column('tournaments', 'maxElo')
    op.drop_column('tournaments', 'minElo')
    # ### end Alembic commands ###
