"""create tournaments table

Revision ID: 1055da0a90ac
Revises: af12127c8119
Create Date: 2026-10-07 09:18:49.575533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1055da0a90ac'
down_revision: Union[str, Sequence[str], None] = 'af12127c8119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INSCRIPTIONS', 'EN_COURS', 'TERMINE', name='tournamentstatus'), nullable=False),
    sa.CheckConstraint('"endDate" >= "startDate"', name='dates_order'),
    sa.CheckConstraint('rounds >= 1', name='rounds_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments')
    sa.Enum(name='tournamentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
