"""create registrations table

Revision ID: 37c3b246c9f4
Revises: 5c1d7e2a9b40
Create Date: 2026-10-07 10:25:28.812932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c3b246c9f4'
down_revision: Union[str, Sequence[str], None] = '5c1d7e2a9b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournamentId'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournamentId', 'userId', name='uq_registration_player')
    )
    op.create_index(op.f('ix_registrations_tournamentId'), 'registrations', ['tournamentId'], unique=False)
    op.create_index(op.f('ix_registrations_userId'), 'registrations', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_userId'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_tournamentId'), table_name='registrations')
    op.drop_table('registrations')
    # ### end Alembic commands ###
