"""create matches table

Revision ID: a3b781d43455
Revises: 37c3b246c9f4
Create Date: 2026-10-07 10:39:37.091299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b781d43455'
down_revision: Union[str, Sequence[str], None] = '37c3b246c9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentId', sa.Integer(), nullable=False),
    sa.Column('whiteId', sa.Integer(), nullable=False),
    sa.Column('blackId', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('NOT_PLAYED', 'WHITE', 'BLACK', 'DRAW', name='matchresult'), nullable=False),
    sa.CheckConstraint('"whiteId" <> "blackId"', name='match_distinct_players'),
    sa.CheckConstraint('round >= 1', name='match_round_min'),
    sa.ForeignKeyConstraint(['blackId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournamentId'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whiteId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournamentId', 'whiteId', 'blackId', name='uq_match_pairing')
    )
    op.create_index(op.f('ix_matches_tournamentId'), 'matches', ['tournamentId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_tournamentId'), table_name='matches')
    op.drop_table('matches')
    sa.Enum(name='matchresult').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
