"""create users table

Revision ID: af12127c8119
Revises: 
Create Date: 2026-09-16 14:47:42.185470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af12127c8119'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.Column('genre', sa.Enum('FILLE', 'GARCON', 'AUTRE', name='genre'), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.CheckConstraint('elo >= 0 AND elo <= 3000', name='elo_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
